services:
  complite-study:
    build: .
    container_name: complite-study
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
    restart: unless-stopped
